name: portfolio

services:
  api:
    container_name: portfolio
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8027:8027
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
