name: portfolio

services:
  api:
    container_name: portfolio
    image: ghcr.io/emilpopovic/portfolio:latest
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    container_name: portfolio_watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup portfolio
    restart: always
